- name: "install Ansible dependencies"
  become: true
  apt:
    name: ["nodejs", "npm", "python3", "tar", "gzip", "git"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: "create the application directory"
  become_user: ubuntu
  become: yes
  file:
    path: ~/app
    state: directory

- name: "untar the backend app file"
  become_user: ubuntu
  become: yes
  unarchive:
    src: ~/project/backend.tar
    dest: ~/app

- name: Build
  become: true
  shell: |
    cd ~/app/backend
    npm install
    npm run build

- name: "start PM2"
  become_user: ubuntu
  become: yes
  shell: |
    cd ~/app/backend
    pm2 start npm --name backend -- start